language: python
python:
- '3.6'
- '3.5'
- '3.4'
- '2.7'
- '2.6'
install:
- if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install importlib unittest2; fi
- pip install -U pip wheel coveralls
- pip install -r requirements/devel.txt
script:
- flake8 . --config=tox.ini
- coverage run --source=pdc_client setup.py test --quiet
after_success:
- coveralls
cache:
  directories:
  - "$HOME/.cache/pip"
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
